global:
  resolve_timeout: 5m

route:
  group_by: [alertname,job]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: default

receivers:
  - name: default
    webhook_configs:
      - url: http://host.docker.internal:9097/webhook
