# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      path_prefix: /


#############################
# Misc
#############################

rule_files:
  - "prometheus.alerts.yaml"
